version: '2'
services:
  frontend:
    image: nginx:alpine
    volumes_from:
      - backend
    ports:
      - "80:80"
    links:
      - backend
    depends_on:
      - backend
    command: sh -c "envsubst '' < /var/www/docker/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/
    links:
      - db
    depends_on:
      - db
    command: sh -c "chmod +x ./docker/init.sh && ./docker/init.sh"
  db:
    image: sameersbn/postgresql
    volumes:
      - ./docker/postrgresql:/var/lib/postgresql
    environment:
      - DB_USER=dev
      - DB_PASS=dev
      - DB_NAME=blog
networks:
  default:
