RashinMe\Entity\Project:
  type: entity
  table: projects
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
      options:
        unsigned: true
  fields:
    name:
      type: string
      length: 175
    description:
      type: text
  oneToOne:
    image:
      targetEntity: RashinMe\Entity\File
      joinColumn:
        name: image_id
        referencedColumnName: id
      cascade:
        - all
  manyToMany:
    tags:
      targetEntity: RashinMe\Entity\Tag
      joinTable:
        name: project_tags
        joinColumns:
          project_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
      cascade:
        - persist
  oneToMany:
    links:
      targetEntity: RashinMe\Entity\Link
      mappedBy: project
      cascade:
        - persist
        - merge
      orphanRemoval: true
